### ISSUE TITLE
pear installation failed

### ISSUE THREAD

**Issue by rkaldung** [phpbrew/Onion#1]
The Onion installation via the pear channel failed:

$ pear install corneltek/Onion-alpha
corneltek/Onion requires PHP extension "reflection" (version >= 0), installed version is $Revision: 313665 $
No valid packages found
install failed

I'm using PHP 5.3.8 w/ Reflection compiled in:

$ php -m | grep -i reflec
Reflection

Looks like the module check is case sensitive.

**Comment by c9s** [comment]
let me check. :-)

does the onion.phar file work for you ?

**Comment by c9s** [comment]
The installation should be fine.

```
sudo pear install -f corneltek/Onion-alpha 
warning: corneltek/Onion requires PHP extension "reflection" (version >= 0), installed version is $Revision: 313665 $
downloading Onion-0.0.2.tgz ...
Starting to download Onion-0.0.2.tgz (43,977 bytes)
............done: 43,977 bytes
install ok: channel://pear.corneltek.com/Onion-0.0.2
```

**Comment by c9s** [comment]
I've update the channel, please try it again. :-)

**Comment by rkaldung** [comment]
Got it. Now, there is an onion.phar ;-)
