### ISSUE TITLE
Featured Request : A dot in package name

### ISSUE THREAD

**Issue by harikt** [phpbrew/Onion#10]
Hi , 

Nice work . @auraphp would like to use it for creating packages for Aura . But a dot in the package name gives some errors.

```
Error: Channel validator error: field "name" - package name "Aura.Di" is invalid
Parsing of package.xml from file "package.xml" failed
Cannot package, errors in package file
Done.
```

Example : package.ini     

```
[package]
name = Aura.Di
desc = package description
version = 0.0.1
channel = pear.php.net
author = Hari K T <mail@example.com>
```

We will be happy if you can make a fix for it .

Also please note that @pyrus already have allowed dot in package name as per the request by @pmjones . See https://github.com/pyrus/Pyrus/issues/75 and https://github.com/pyrus/Pyrus/issues/80

**Comment by harikt** [comment]
Aaah I just noticed that it depends on pear :( . https://github.com/c9s/Onion/blob/master/src/Onion/Command/BuildCommand.php#L88

**Comment by c9s** [comment]
Hi Harikt,

Onion's long term target is to drop the PEAR dependencies, 
but for now, we need the PEAR channel to distribute packages. :-)

If you only need `bundle` feature, you don't need PEAR for this.

**Comment by c9s** [comment]
Ah, wait, if you mean Pyrus, I can add an option not to build package with PEAR.  :-)

So right, this will be a feature. :-)

**Comment by harikt** [comment]
@c9s ok , I will wait to see the outcome :-) .

Currently https://github.com/auraphp/release can build for for composer, we are looking for a way to build pear packages.

Thank you .

**Comment by c9s** [comment]
Hi @harikt,

check out this: https://github.com/c9s/Onion/commit/90d8f6e98546b4b35dc28aec50074b2a7985ac11

```
  onion.phar -d build
```

This won't depend on pear. :-D

```
  onion.phar -d build --pyrus
```

to build with pyrus

**Comment by harikt** [comment]
ie so cool , and Thank you for the quick fix . Hope @pmjones will be Happy to see this :-) .

**Comment by pmjones** [comment]
Sweet.

**Comment by c9s** [comment]
Does this solve your problem ? :-)

**Comment by harikt** [comment]
Yes, as it has nothing to do other than making the pear package via pear / pyrus this fix will help. Though seeing this for the first time I thought it will build the pear package without pear or pyrus :-) .

**Comment by c9s** [comment]
Hi,

yes, we'd like to have a built-in builder for pear package. but I am too busy now. 

patches are welcome. :-)

**Comment by harikt** [comment]
@c9s yes I may want to look , how the packaging works . I wonder its just creating a tar.gz reading the xml . Then seems easy . Not sure though .

**Comment by c9s** [comment]
@harikt Pyrus does some validation by using xsd , there are some sample code of this. it's not hard i guess. :-)

**Comment by harikt** [comment]
ok , I will check :)
