### ISSUE TITLE
Onion.phar

### ISSUE THREAD

**Issue by harikt** [phpbrew/Onion#11]
Hi @c9s , 

I guess the onion.phar got corrupted . Please check .

**Comment by c9s** [comment]
it works fine for me, what's the problem? :-)

can you paste the error ?

**Comment by harikt** [comment]
It throws some html . 

```
 $ wget https://github.com/c9s/Onion/blob/master/onion.phar 
```

But its going in wrong path I guess . Can you try downloading the file ?

**Comment by harikt** [comment]
Not able to download the phar only . See http://pastie.org/3202601

**Comment by harikt** [comment]
hm , I guess I want to download the whole files 

```
  $ git clone https://github.com/c9s/Onion.git
```

to get the onion.phar .

**Comment by harikt** [comment]
Good if we can download phar seperately . Do you know how we can place in downloads ?

**Comment by c9s** [comment]
The url you used is redirected.

In our readme.md :-)

```
$ curl -s http://install.onionphp.org/ | sh
```

This can get and install Onion.

Or your can download directly:

```
 curl -# -O https://raw.github.com/c9s/Onion/master/onion.phar
```

**Comment by c9s** [comment]
Dear @harikt, 

I just placed a Hacking section in README.md if you need it. :-)

**Comment by harikt** [comment]
Thank you . I use wget more than curl :) . So for me 

```
 $ wget https://raw.github.com/c9s/Onion/master/onion.phar
```

**Comment by alganet** [comment]
There is no onion.phar anymore? =(

**Comment by c9s** [comment]
It's renamed to "onion" instead of "onion.phar".  :-)
