### ISSUE TITLE
docs vs doc

### ISSUE THREAD

**Issue by harikt** [phpbrew/Onion#15]
Hi , 

When looking through 

http://pear.php.net/manual/en/pear2cs.rules.php

I feel the docs is pear name , than doc , where yours looks for doc .

What do you think ? Atleast look for docs too ?

**Comment by harikt** [comment]
Currently this is my package.ini file and it still reports the error 

```
Checking directory structure...
    * doc/ directory not found.
Configuring package.ini
Reading config file: package.ini
Configuring dependencies...
Writing package.xml...
Building contents section...
Building dependencies section...
Building phprelease section...
package.xml is generated. you can now build your PEAR package with:

PEAR:

    $ pear -q package

Pyrus:

    $ pyrus.phar package
Done.
```

The `package.ini` is 

```
[package]
name = Aura.Autoload
desc = The Aura Autoload package provides a PSR-0 compliant SPL autoloader implementation for PHP. It also matches the proposed SplClassLoader interface.
version = 1.0.0beta2
channel = pear.php.net
author = Paul M Jones <hismailid@gmail.com>

[require]
php = 5.4
pearinstaller = 1.4

[roles]
docs = doc
```

**Comment by c9s** [comment]
Sure, I'd like to change `doc` to `docs`. patches are welcome. :-)

**Comment by harikt** [comment]
lol :D . Let me see what I can do :-)

**Comment by harikt** [comment]
Can I rename `doc` to `docs` or do we need to place `is_dir( docs ) || is_dir( doc)`

**Comment by c9s** [comment]
Rename doc to docs is fine. :-)

I also like `is_dir( docs ) || is_dir( doc)`.  its more smarter.

On Mon, Feb 20, 2012 at 1:10 AM, Hari K T
reply@reply.github.com
wrote:

> Can I rename `doc` to `docs` or do we need to place `is_dir( docs ) || is_dir( doc)`
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/c9s/Onion/issues/15#issuecomment-4043361

## 

Best Regards,

Yo-An Lin

**Comment by harikt** [comment]
Hi , 

I am facing some issues with phpunit so was not able to test . But have changed the places where I feel its working .

Can you test from a different branch fetching from my fork and merge if its ok ?

https://github.com/harikt/Onion

**Comment by c9s** [comment]
Sure. :-)

**Comment by c9s** [comment]
Fixed and merged.  thanks for that patch.  :-D

**Comment by harikt** [comment]
You are welcome and Thank you for doing the remaining :-)
