### ISSUE TITLE
Custom structure does not work

### ISSUE THREAD

**Issue by augustohp** [phpbrew/Onion#16]
We use in our projects mainly the **library** instead of **src** as the container for the source code, I tried many variations of the configuration, using roles, modifying the structure and nothing seemed to work.

Am I missing something?

``` ini
[package]
name = Respect\Validation
desc = The most awesome validation engine ever created for PHP
homepage = http://respect.li
version = 1.0.0
channel = respect.li/pear
repository = github.com/Respect/Validation
authors[] = Alexandre Gaigalas <alexandre@gaigalas.net>
authors[] = Augusto Pascutti <augusto@phpsp.org.br>
authors[] = Henrique Moody <henrique.moody@gmail.com>

[structure]
src  = library

[requires]
php = '>= 5.3.5'
extensions[] = 'reflection'
extensions[] = 'ctype'
extensions[] = 'pcre'
```

**Comment by c9s** [comment]
Hi!

The spec was changed, and I am still thinking new features. :-)

You can specify [roles] section to include your library. :-)

[roles]
library = src

;  {path} = {role}
;  {glob path} = {role}

And the require section is like:

[require]
php = 5.3
pearinstaller = 1.4
; other pear dependencies ..

On Tue, Mar 27, 2012 at 10:37 AM, Augusto Pascutti <
reply@reply.github.com

> wrote:
> 
> We use in our projects mainly the **library** instead of **src** as the
> container for the source code, I tried many variations of the
> configuration, using roles, modifying the structure and nothing seemed to
> work.
> 
> Am I missing something?
> 
> ``` ini
> [package]
> name = Respect\Validation
> desc = The most awesome validation engine ever created for PHP
> homepage = http://respect.li
> version = 1.0.0
> channel = respect.li/pear
> repository = github.com/Respect/Validation
> authors[] = Alexandre Gaigalas <alexandre@gaigalas.net>
> authors[] = Augusto Pascutti <augusto@phpsp.org.br>
> authors[] = Henrique Moody <henrique.moody@gmail.com>
> 
> [structure]
> src  = library
> 
> [requires]
> php = '>= 5.3.5'
> extensions[] = 'reflection'
> extensions[] = 'ctype'
> extensions[] = 'pcre'
> ```
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/c9s/Onion/issues/16

## 

Best Regards,

Yo-An Lin

**Comment by alganet** [comment]
Awesome! Me and @augustohp developed a custom pear packager and we've been thinking on moving from it to Onion due to its great API. Definitely gonna try this today.

**Comment by c9s** [comment]
Thanks :-)

I modified your ini file, try this, see if that works.  

https://gist.github.com/2216557

**Comment by c9s** [comment]
oh BTW, I did expect that the channel format `respect.li/pear` is a valid channel, so .. I am not so sure this channel format is workable for `bundle` command, but for `build` command , I think that's fine.

**Comment by alganet** [comment]
Whats the difference between build and bundle?

**Comment by c9s** [comment]
Bundle command, is like ruby bundler, which can download & install dependencies into current dir (vendor/pear).

Build command, can build package.xml file for PEAR packages.  :-)

**Comment by augustohp** [comment]
@c9s The `respect.li/pear` is a valid pear channel and we already use it today =D

I tests the INI you provided and received the same output error that i added into your gist as a comment.

**Comment by alganet** [comment]
Got custom structure working with:

``` ini
[package]
name = Rest
desc = Thin Controller for RESTful applications
version = 1.0.0
channel = pear.php.net
author  = Alexandre Gaigalas <alexandre@gaigalas.net>

[roles]
library = src
```

Thanks!

**Comment by c9s** [comment]
Congratulations !
