### ISSUE TITLE
Redeclaring custom roles duplicates files on package.xml

### ISSUE THREAD

**Issue by alganet** [phpbrew/Onion#18]
At Respect\Foundation, we're building an automated package.ini generator that gathers information from folder structure, git and other files.

From this info, we infer the PHP roles from the directories. For example, if the user has the "lib" folder, its automatically added to the php role. Same happends for the "src" folder and others.

Seems that re-declaring default roles leads to duplication of file tags in the generated package.xml. Other default roles has the same problems, such as "tests".

I've added defensive code on my own project to prevent this and lost my samples, but I can simulate the problem and submit a test case if you need.

**Comment by c9s** [comment]
The [roles] section will be merged with default roles,

Maybe we can change it to:

if [roles] is specified, don't use default roles.

I need time to change this. :-)

Thanks

**Comment by alganet** [comment]
No problem! I'm gonna work on this change =D
