### ISSUE TITLE
Pyrus breaks when installing packages built with Onion

### ISSUE THREAD

**Issue by nrk** [phpbrew/Onion#2]
Onion generates `package.xml` files specifing `version="2.0"` and using the XSD of [package-2.0](http://pear.php.net/dtd/package-2.0.xsd). The problem is that the `install-as` attribute used by Onion in `file` elements is not allowed in this version and [Pyrus](http://pear.php.net/manual/en/pyrus.php), which performs XML validation using the XSD, refuses to install our packages lamenting that the XML in `package.xml` is malformed.

Instead of the `install-as` attribute in `file` elements, it would be probably better to use the `phprelease` node e.g.:

```
<phprelease>
    <filelist>
        <install name="Predis/Client.php" as="Predis/Client.php" />
        <!-- rest of the list -->
    <filelist>
</phprelease>
```

**Comment by c9s** [comment]
Is this phprelease/filelist tag supported in PEAR installer (1.4) ?

**Comment by c9s** [comment]
Ok I found the same spec usage in symfony/YAML, will try to fix this later. :-)

**Comment by nrk** [comment]
Not sure, I just dug a little into the specs but I'm definitely not an expert of PEAR :-) Maybe you can implement two different package generators: one that generates a `package.xml` for older versions of the PEAR installer and one that works with newer versions (if they are not compatible), with a flag to switch between them that can be specified via command-line arguments or in the `package.ini` file.

**Comment by c9s** [comment]
Hi! I've finished the phprelease tag support on develop branch

Pyrus doesn't work for me for any package

Can you try this commit 5e9aabf8140525f012d1d0e149f9e25d9db0f4d5 with Pyrus ?  Thanks  :-)

**Comment by c9s** [comment]
I've fixed another issue (active attribute). it seems pretty hard to satisfied Pyrus. hate this..

**Comment by nrk** [comment]
Now with the fix for `active`, the `package.xml` file in the PEAR package of Predis passes the validation. At least I'm able to get details out of it with `php pyrus.phar info Predis-0.7.1.tgz` since I can't seem to be able to install anything due to problems in my environment (will try on another computer).

**Comment by c9s** [comment]
I'm now sure the phprelease/filelist tag is supported in PEAR 1.4.  

And have tested with `active` fix. pyrus installer works fine.  :-)

**Comment by nrk** [comment]
Alright everything seems to work here too if I remove the files in the `bin` role but it's definitely an issue related to Pyrus (see [this post on the mailing list](http://old.nabble.com/Installing-PEAR2-Pyrus-td31472653.html)).

Is it possible to tell Onion to ignore certain files / path when building a package? For Predis I don't really need to ship the files in the `bin` since they are utilities scripts for development. If it's not supported I can open a new issue for a feature request so you can close this one as I think you can consider it fixed.

**Comment by c9s** [comment]
Sure. I will provide some options for this kind of requirements later. 

Let's close this issue.

**Comment by c9s** [comment]
@nrk I've remove the default bin role for now, will think a better solution for this. :-)

you can try to master branch version.

**Comment by nrk** [comment]
It seems to work. Looking forward for a definitive solution, thanks!

**Comment by c9s** [comment]
You're welcome. :-)

On Sun, Jan 1, 2012 at 9:44 PM, Daniele Alessandri <
reply@reply.github.com

> wrote:
> 
> It seems to work. Looking forward for a definitive solution, thanks!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/c9s/Onion/issues/2#issuecomment-3324526

## 

Best Regards,

Yo-An Lin
