### ISSUE TITLE
An article for Onion

### ISSUE THREAD

**Issue by jaceju** [phpbrew/Onion#27]
幫 Onion 寫了個介紹，看適不適合放到 README 上。

[如何利用 Onion 管理 PHP 專案](http://www.openfoundry.org/tw/tech-column/8779--onion-php-)

**Comment by c9s** [comment]
Cool! 鐵神++

看能不能放到 README.zh_TW ?

**Comment by jaceju** [comment]
已經送 Pull Request 了 :)

**Comment by c9s** [comment]
Thanks!!!
